//
var lans = {
  "cn":{
"Network status":"网络数据 ",
"Economics":"通证经济 ",
"Block Height":"区块高度 ",
"Block Time":"出块时间 ",
"Epoch":"轮/期 ",
"Until Epoch End":"本轮结束倒计时 ",
"Groups":"验证组 ",
"Elected/Registered":"已当选/已注册 ",
"Validators":"验证人 ",
"Locked cGLD":"已锁定的cGLD ",
"Votes":"投票总数 ",
"cGLD Price":"cGLD价格 ",
"Allocated Supply":"发行总量 ",
"Circulating supply based on the model":"当前流通量基于此经济模型 ",
"Address/Transfers":"地址数/交易数 ",
"Incremental Supply cGLD":"cGLD递增供应 ",
"Incremental Supply cUSD":"cUSD递增供应 ",
"Like what we do? Support thecelo by making a donation!":"喜欢这个网站吗？捐助我们来帮助网站进一步发展吧！ ",
"LockedGold Rate=LockedGold/TotalSupplyGold":"Gold锁定率=Gold锁定量/总供应量 ",
"Votes Rate=Votes/TotalSupplyGold":"投票率=投票总量/总流通量 ",
"Incremental Supply cGLD=((Current Epoch TotalSupply cGLD)-(1th Epoch TotalSupply cGLD))/(1th Epoch TotalSupply cGLD)":"cGLD供应增长率=（当前轮cGLD供应量—第1轮cGLD总供量）/第一轮cGLD供应量 ",
"Incremental Supply cUSD=((Current Epoch TotalSupply cUSD)-(1th Epoch TotalSupply cUSD))/(1th Epoch TotalSupply cUSD)":"cUSD供应增长率=（当前轮cUSD供应量—第1轮cUSD总供量）/第一轮cUSD供应量 ",
"Groups":"验证组 ",
"Validators":"验证人 ",
"Total Voting Power":"总投票权 ",
"Elected Minimum Votes":"当选最低投票数 ",
"Voting Power ":"投票权 ",
"Cumulative Share":"累计份额占比 ",
"Capacity":"投票容量 ",
"Commission ":"佣金 ",
"Score":"得分 ",
"Elected/Total":"已当选/所有验证组 ",
"Domain":"域名 ",
"Metadata":"元数据 ",
"Commission":"佣金 ",
"Next Commission":"下一轮佣金 ",
"Next Commission Block":"下一轮佣金生效区块 ",
"Slashing Multiplier":"处罚倍数 ",
"Last Slashed":"最近一次被处罚 ",
"Members Updated":"组成员更新 ",
"Available cGLD":"可用的cGLD ",
"Locked cGold":"已锁定的cGold ",
"Pending cGold":"待启用的cGold ",
"Available cUSD":"可用的cUSD ",
"Total cGold":"cGold总计 ",
"Domain proven":"域名是否验证 ",
"Can receive votes":"是否可接受投票 ",
"Participated in TGCSO":"是否参加TGCSO ",
"Will get elected":"下轮是否当选 ",
"Secure":"是否安全 ",
"Reliable":"是否稳定 ",
"No recent slashing":"近期未收到处罚 ",
"Runs an Attestation Service":"提供测试验证服务 ",
"Runs a Validator on Baklava":"在Baklava测试网运行节点 ",
"Receives Celo Foundation votes":"接受过Celo基金会投票 ",
"Promotes the Celo mission":"推动了Celo愿景的实现 ",
"Broadens Diversity":"有多样化拓展行为 ",
"Participates in the community":"是否参加社区生态建设 ",
"voting#choosing a validator group guide":"如何选择验证组指南 ",
"Active Votes":"生效投票数 ",
"Pending Votes":"待激活投票数 ",
"Remaining Votes Receivable":"可接受投票余额数 ",
"Total Votes":"总投票数 ",
"Score":"得分 ",
"Available cGLD":"可用的cGLD ",
"Locked cGold":"已锁定的cGold ",
"Available cUSD":"可用的cUSD ",
"Pending cGLD":"待启用的cGold ",
"Total cGLD":"总cGLD ",
"Elected":"是否当选 ",
"Frontrunner":"下一轮是否当选 ",
"Rank":"排名 ",
"Info":"基本信息 ",
"Balance":"余额 ",
"Identify":"认证信息 ",
"Total Voting Capacity":"总投票能力 ",
"validators of the group":"验证组中的验证人 ",
"validator":"验证人 ",
"Score ":"得分 ",
"Elected ":"是否当选 ",
"Frontrunner":"下轮是否当选 ",
"Attestation":"SMS验证服务 ",
"uptime":"在线率 ",
"Validator score is the exponential moving average of their epoch scores.":"验证人得分是他们每轮得分的指数均值 ",
"Elected is whether the cuurent epoch is elected.":"指当前轮该验证人是否当选 ",
"Frontrunner is whether the next epoch will be elected, according to the current votes.":"指下一轮该验证人是否会当选 ",
"Attestation is the arte at which vcalidator successfully sends signed SMS messages.":"验证人是否成功发送带有签名的SMS消息服务的比率 ",
"Uptime is the percentage of 12-block windows that include at least one signature of the given validator.":"指定验证人在12个出块中至少带有一个签名的比率 ",
"account":"账户 ",
"supply":"总供应量 ",
"Addresses":"地址数 ",
"Transfers":"交易数 ",
"LockedGold":"已锁定Gold ",
"Cumulative Share":"累计份额占比 ",
"Percentage (Total Supply)":"总供应量百分占比 ",
"Txs":"txs ",
"governance":"治理 ",
"Pass":"已通过 ",
"Reject":"已否决 ",
"Voting":"投票中 ",
"Excuted":"已执行 ",
"Proposer":"发起者 ",
"Deposit":"保证金/抵押金 ",
"Date":"日期 ",
"Upvoters":"赞成者 ",
"Addresses":"地址数 ",
"Upvotes":"赞成投票数 ",
"Dequeue":"出列者 ",
"Approval":"批准者 ",
"Voters":"投票者 ",
"Executor":"执行者 ",
"Unfreeze Celo Gold Transfers":"开启Celo Gold交易 ",
"Unfreeze Voter Rewards":"开启投票奖励 ",
"Unfreeze Election contract":"运行选举智能合约 ",
"cGLD Token Release Schedule":"cGLD代币释放时间表 ",
"Token Allocation ":"代币分配总览 ",
"Year":"按年度 ",
"Type":"按类型 ",
"Pre-launch sales	":"上线前预售 ",
"Team, Advisors,Founders and Contributors":"团队、顾问、创始人和贡献者 ",
"Staking & Validator Rewards (thru 3/2050)":"质押&验证人奖励（至3/2050) ",
"Community Grants (Thru 3/2050)":"社区资助（至3/2050) ",
"Operational Grants	":"其余业务资助 ",
"Inital Reserve	":"原始储备金 ",
"Total":"共计 ",
"% of Total Supply	":"占总供应量百分比 ",
"Circulating Supply (without reserve)	":"流通总量（含储备金） ",
"Circulating Supply (including reserve)	":"流通总量（不含储备金） ",
"Circulating Supply %	":"流通总量占比 ",
"Incremental Supply %	":"供应增长率 ",
"Monthly Supply With Epoch Rewards	":"每轮奖励的月度供应量 ",
"Circulating Supply as a % of Current Supply":"流通总量/当前总供应量 ",
"Estimated Circulating Supply* ":"预估流通总量 ",
"Total Allocated to Initial Reserve":"原始储备金的全部分配 ",
"Total Allocated":"全部分配 ",
"T+1 Year	":"T+1 年  ",
"T+10 Years	":"T+10 年 ",
"Total":"共计 ",
"T+1/Total":"T+1/共计 ",
"Assume no change in the reserve, currently a 1:1 ratio between cGLD and total digital assets in the reserve":"假设储备金没有变动，cGLD和储备的全部数字资产当前应是1:1比例。 ",
"Network Stats":"网络数据 ",
"cUSD/cGLD Prices":"cUSD/cGLD价格 ",
"LockedGold / Votes":"已锁定Gold/投票数 ",
"Groups":"验证组 ",
"Validators":"验证人 ",
"Response":"回传参数 ",
"request":"请求参数 ",
"mainnet":"主网 ",
"Testnet Baklava":"Baklava测试网 ",
"0 : Total Blocks":"总出块数 ",
"1 : Average Block Time":"平均出块时间 ",
"2 : Blocks until Epoch":"每轮出块数 ",
"3 : Epoch Size":"每轮大小 ",
"4 : Total Transactions":"全部交易 ",
"5 : Gas Price":"燃油费 ",
"6 : cGLD Price":"cGLD价格 ",
"7 : cUSD Price":"cUSD价格 ",
"8 : Market Cap":"市值 ",
"9 : Active Nodes":"在线节点 ",
"10 : Elected Groups":"当选验证组 ",
"11 : Registered Groups":"注册验证组 ",
"12 : Elected Validators":"当选验证人 ",
"13 : Registered Validators":"注册验证人 ",
"14 : cGLD totalSupply":"cGLD总供应量 ",
"15 : cGLD addresses":"cGLD地址数 ",
"16 : cGLD transfers":"cGLD交易数 ",
"17 : cUSD totalSupply":"cUSD总供应量 ",
"18 : cUSD addresses":"cUSD地址数 ",
"19 : cUSD transfers":"cUSD交易数 ",
"mainnet":"主网 ",
"Testnet Baklava":"Baklava测试网 ",
"exchange_prices[0-n]":"交易价格 ",
"mainnet":"主网 ",
"Testnet Baklava":"Baklava测试网 ",
"cgld_total_supply":"cGLD总供应量 ",
"locked_gold ":"已锁定gold ",
"key : epoch":"每轮钥匙 ",
"value ":"价值 ",
"totalLockedGold":"全部已锁定Gold ",
"totalVotes":"总投票数 ",
"nonvotingLockedGold":"未投票的已锁定Gold ",
"timestamp":"时间戳 ",
"groups{}":"验证组 ",
"key : address":"钥匙：地址 ",
"value : []":"价值 ",
"0 : Group Name":"验证组名字 ",
"1 : Votes":"投票数 ",
"2 : Capacity":"验证组权力 ",
"3 : ElectedCount":"记为当选 ",
"4 : MemberCount":"记为组成员 ",
"5 : eligible":"合格 ",
"6 : commission":"佣金 ",
"7 : logo":"商标 ",
"8 : score":"分数 ",
"timestamp":"时间戳 ",
"rank":"排名 ",
"group[]":"验证组 ",
"0 : Address":"地址 ",
"1 : GroupName":"验证组名字 ",
"2 : Votes":"投票数 ",
"3 : cGld":"cGld ",
"4 : LockedcGLD":"已锁定GLD ",
"5 : cUSD":"cUSD ",
"6 : Total":"总计 ",
"7 : Commission":"佣金 ",
"8 : nextCommission":"下一轮佣金 ",
"9 : nextCommissionBlock":"下一轮佣金生效区块 ",
"10 : slashingMultiplier":"处罚倍数 ",
"11 : lastSlashed":"上次被处罚 ",
"12 : MembersUpdated":"组成员更新 ",
"13 : members / validators [n]":"组成员/验证人 ",
"0 : Validator Name":"验证人名字 ",
"1 : Validator Address":"验证人地址 ",
"2 : Score(Uptime)":"得分（在线时间） ",
"3 : Pending cGLD":"待启用cGLD ",
"4 : Active cGLD":"已激活cGLD ",
"5 : Elected":"当选 ",
"6 : cGLD":"cGld ",
"7 : LockedGold":"已锁定GLD ",
"8 : cUSD":"cUSD ",
"9 : Total":"总计 ",
"10 : signer":"签名者 ",
"11 : frontrunner":"下一轮是否当选 ",
"12 : proposed":"提议 ",
"13 : signatures":"签名 ",
"SignerAddress":"签名人地址 ",
"totalcGld":"总cGLD ",
"totalcUSD":"总cUSD ",
"cgld_total_addresses":"cGLD总地址数 ",
"cusd_total_addresses":"cUSD总地址数 ",
"cusd_total_transfers":"cUSD总交易数 ",
"accounts{}":"账户数 ",
"key : address":"钥匙：地址 ",
"value : [0-n]":"价值 : [0-n] ",
"5 : nonVotingLockedGold":"未投票的已锁定Gold ",
"6 : pendingWithdrawals":"待启用的撤回Cgld ",
"7 : metadataURL":"metadata链接 ",
"items[0...n]":"类目 ",
"key : id":"钥匙：id ",
"value : {n}":"价值 ",
"status":"状态 ",
"timespan":"时间跨度 ",
"title":"标题 ",
"desc":"描述 ",
"proposer":"提议人 ",
"address":"地址 ",
"deposit":"保证金 ",
"timestamp":"时间戳 ",
"upvoted":"赞成 ",
"addresses":"地址数 ",
"upvotes":"赞成投票数 ",
"dequeue":"出列 ",
"address":"地址 ",
"timestamp":"时间戳 ",
"approval":"批准 ",
"address":"地址 ",
"timestamp":"时间戳 ",
"voted":"投票 ",
"addresses":"地址数 ",
"weight":"高度 ",
"executed":"执行 ",
"from":"从 ",
"blockNumber":"区块编号 ",
"transactionHash":"交易哈希值 ",
"items_vote[1...n]":"类目_投票 ",
"['Yes/No/Abstain',0]":"是/否/弃权 ",
"Exchange":"交易 ",
"Election":"选举 ",
"Attestations":"SMS验证服务 ",
"LockedGold":"锁定中Gold ",
"SortedOracles":"排序预测 ",
"GasPriceMinimum":"最小Gas价格 ",
"Reserve":"储备金 ",
"StableToken":"稳定币 ",
"DowntimeSlasher":"离线处罚 ",
"Spread: 0.005":"点差：0.005 ",
"ReserveFraction: 0.01":"储备分数：0.01 ",
"UpdateFrequency: 5 Minutes":"更新频率：5分钟 ",
"MinimumReports: 5":"最小要求Gold：5 ",
"LastBucketUpdate 0":"最后一次更新 ",
"ElectableValidators:":"验证人可选举数 ",
"Min: 22":"最少：22 ",
"Max: 100":"最多：100 ",
"ElectabilityThreshold":"选举阈值 ",
"MaxinumGroupsVotedFor":"验证组投票人上限 ",
"TotalVotes":"投票总数 ",
"CurrentThreshold":"当前阈值 ",
"AttestationExpiryBlocks":"短消息验证有效期块数 ",
"AttestationRequestFees":"短消息验证请求费 ",
"Fee":"费用 ",
"Address ":"地址 ",
"Fee":"费用 ",
"Address ":"地址 ",
"ConcurrentProposals: 3":"当前提案数 ",
"DequeueFrequency: 1day":"出队频率：1天 ",
"MinDeposit: 100cGLD":"最小充值 ",
"QueueExpiry: 28 Days":"队列到期时间：28天 ",
"StageDurations:":"阶段时长 ",
"Approval: 1day":"批准期：1天 ",
"Referendum: 2 Days":"公投期：2天 ",
"Execution: 3 Days":"执行期：3天 ",
"ParticipationParameters":"参与参数 ",
"Baseline 0.0991838708624":"基线 0.0991838708624 ",
"BaselineFloor 0.05":"基准底线 0.05 ",
"BaselineUpdateFactor 0.2":"基线更新因子 0.2 ",
"BaselineQuorumFactor 1":"基线法定人数因子 1 ",
"UnlockingPeriod: 3 Days":"解锁时长：3天 ",
"TotalLockedGold ":"已锁定Gold总数 ",
"ReportExpirySeconds":"报告到期秒数： 5分钟 ",
"GasPriceMinimum: 100000000":"最小Gas价格：100000000 ",
"TargetDensity: 0.5":"目标密度：0.5 ",
"AdjustmentSpeed: 0.5":"调整速度：0.5 ",
"TobinTaxStalenessThreshold: 3153600000":"托宾税收陈旧度阈值：3153600000 ",
"FrozenReserveGoldStartBalance 0":"冻结中储备Gold启用余额 ",
"FrozenReserveGoldStartDay 18374":"冻结中储备Gold启用时间 ",
"FrozenReserveGoldDays 0":"冻结中储备Gold启用天数 ",
"OtherReserveAddresses":"其余储备地址数 ",
"Name: Celo Dollar":"名称：Celo Dollar ",
"Symbol: CUSD":"代号：CUSD ",
"Decimals: 18":"小数点：18 ",
"InflationParameters:":"通胀参数： ",
"Rate: 1":"通胀率：1 ",
"Factor: 1":"调整因子：1 ",
"UpdatePeriod: 547 Days 12 Hours":"更新周期：547天12小时 ",
"FactorLastUpdated: 1587586863":"最后更新时间：1587586863 ",
"ValidatorLockedGoldRequirements:":"验证人Gold锁定要求： ",
"Value: 10000cGLD":"数量：10000cGLD ",
"Duration: 60 Days":"时长：60天 ",
"GroupLockedGoldRequirements:":"验证组Gold锁定要求： ",
"Value: 10000cGLD":"数量：10000cGLD ",
"Duration: 180 Days":"时长：180天 ",
"Max Group Size: 5":"验证组最多容纳验证人数： 5 ",
"Membership HistoryLength 60":"组成员历史长度：60 ",
"Slashing Multiplier Reset Period 2592000":"SlashingMultiplierResetPeriod 2592000 ",
"Commission Update Delay 51840":"CommissionUpdateDelay51840 ",
"SlashableDowntime 5760":"将受处罚的离线时长 ",
"validator form":"验证人表格 ",
"Mainnet Group Addresses":"主网验证组地址 ",
"Password":"密码 ",
"Remember me":"保持登录状态 ",
"Submit":"提交 "
      }
  };
